version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes: 
            - esdata:/usr/shre/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - esnet
        restart: always
    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        volumes:
            - ./kibana.yml/:/usr/share/kibana/config/kibana.yml
        ports: 
            - "5601:5601"
        depends_on: 
            - elasticsearch
        networks: 
            - esnet
        restart: always

volumes: 
    esdata:
        driver: local

networks: 
    esnet:
